hover card project finishedhttps://github.com/NextGenDevOrg/04-Project-Showcase/pull/23
NextGenDevOrg/04-Project-Showcase pull request #24
Opened 2021-12-31 07:33 UTC by Kiran-512

Hi, Apologies for pushing the entire code in one go as the project was already completed. 

can check live here: https://kiran-512.github.io/hover-cards/

2022-01-01 12:56 UTC, Kiran-512 commented
Please review the code, have created the hovercard project in a different way. 

I also need help even after applying the sticky position to the header it's not working. please suggest

2022-01-02 07:48 UTC, Abbas4tech requested changes

2022-01-02 07:48 UTC, Abbas4tech commented on tasks-by-users/Kiran-Yadav/01-project-hovercard/assets/style.css
> +  display: flex;
group similar properties @Kiran-512

2022-01-02 07:48 UTC, Abbas4tech commented on tasks-by-users/Kiran-Yadav/01-project-hovercard/effective.html
> +    </style>
check whether your prettier is working or not? and also remove embedded styling @Kiran-512

2022-01-22 13:57 UTC, closed without merging